### ISSUE TITLE
www-client/ungoogled-chromium: issues with 'esbuild'

### ISSUE THREAD

**Issue by itZzenXX** [PF4Public/gentoo-overlay#142]
Hi! I am currently trying to build ungoogled-chromium 100 but this error occurs which seems to be related to esbuild:
```
ninja: error: '../../third_party/devtools-frontend/src/third_party/esbuild/esbuild', needed by 'gen/third_party/devtools-frontend/src/inspector_overlay/common.js', missing and no known rule to make it
```
build log:
[build.log](https://github.com/PF4Public/gentoo-overlay/files/8406915/build.log)
notes:
I am using musl libc on my system.

**Comment by itZzenXX** [comment]
just looked through my user patches, none of them include any reference to esbuild or devtools-frontend

**Comment by PF4Public** [comment]
Did 99 work?

**Comment by itZzenXX** [comment]
99 did get further, but I have this error:
```
/usr/include/sys/cdefs.h:4:2: warning: usage of non-standard #include <sys/cdefs.h> is deprecated [-W#warnings]
#warning usage of non-standard #include <sys/cdefs.h> is deprecated
 ^
../../base/allocator/allocator_shim_default_dispatch_to_partition_alloc.cc:666:36: warning: 'mallinfo' has C-linkage specified, but returns incomplete type 'struct mallinfo' which could be incompatible with C [-Wreturn-type-c-linkage]
SHIM_ALWAYS_EXPORT struct mallinfo mallinfo(void) __THROW {
                                   ^
../../base/allocator/allocator_shim_default_dispatch_to_partition_alloc.cc:666:36: error: incomplete result type 'struct mallinfo' in function definition
../../base/allocator/allocator_shim_default_dispatch_to_partition_alloc.cc:666:27: note: forward declaration of 'mallinfo'
SHIM_ALWAYS_EXPORT struct mallinfo mallinfo(void) __THROW {
                          ^
../../base/allocator/allocator_shim_default_dispatch_to_partition_alloc.cc:691:19: error: variable has incomplete type 'struct mallinfo'
  struct mallinfo info = {0};
                  ^
../../base/allocator/allocator_shim_default_dispatch_to_partition_alloc.cc:666:27: note: forward declaration of 'mallinfo'
SHIM_ALWAYS_EXPORT struct mallinfo mallinfo(void) __THROW {
                          ^
2 warnings and 2 errors generated.
```

**Comment by PF4Public** [comment]
@git-bruh I remember you used ungoogled-chromium with musl. Did you have any such issues? May we ask for your assistance :)

**Comment by git-bruh** [comment]
@PF4Public That particular error should be fixed by `use_allocator=\"none\"` and `use_allocator_shim=false`

Also u need 10-20 extra patches https://github.com/kiss-community/community/tree/main/community/chromium/patches, everything here starting with `musl-`. Especially `musl-tid-caching.patch` if you don't want tabs to crash every few minutes

**Comment by PF4Public** [comment]
@git-bruh Thank you very much!

@itZzenXX Please try as suggested and let me know of the outcome.

**Comment by itZzenXX** [comment]
I still get the same error, how can I put in these variables in portage? I've been using a package.env

**Comment by PF4Public** [comment]
You should use `EXTRA_GN='use_allocator=\"none\" use_allocator_shim=false'`

**Comment by itZzenXX** [comment]
I put that in package.env?

**Comment by PF4Public** [comment]
> I put that in env/chromium?

Yes

**Comment by itZzenXX** [comment]
ok, added

**Comment by itZzenXX** [comment]
aparently it errors out as it has no idea what the '\' token is. Should I just use ``EXTRA_GN='use_allocator="none" use_allocator_shim=false'``?

**Comment by PF4Public** [comment]
@itZzenXX please do not use issue tracker as a chat. Also please try solving trivial issues yourself first.

**Comment by itZzenXX** [comment]
I got further, but I now have this issue:
```
FAILED: gen/net/data/ssl/ev_roots/[chrome-ev-root-store-inc.cc](http://chrome-ev-root-store-inc.cc/)
python3.9 ../../build/gn_run_[binary.py](http://binary.py/) root_store_tool --root-store-dir=../../net/data/ssl/ev_roots --write-cpp=gen/net/data/ssl/ev_roots/[chrome-ev-root-store-inc.cc](http://chrome-ev-root-store-inc.cc/) --cpp-output-format=ev --write-deps=gen/net/data/ssl/ev_roots/[chrome-ev-root-store-inc.cc](http://chrome-ev-root-store-inc.cc/).d
root_store_tool failed with exit code -4
```

**Comment by PF4Public** [comment]
Have you applied all the patches?

**Comment by PacketOperator** [comment]
I have the same error initial error, but using glibc.  99 built without issue. Forgive my ignorance if this is a stupid question, will adding the build variables above apply to me as well? 

ninja: error: '../../third_party/devtools-frontend/src/third_party/esbuild/esbuild', needed by 'gen/third_party/devtools-frontend/src/inspector_overlay/common.js', missing and no known rule to make it
 * ERROR: www-client/ungoogled-chromium-100.0.4896.75_p1::pf4public failed (compile phase):
 *   ninja -v -j33 -l33 -C out/Release v8_context_snapshot_generator failed

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let me know.
Closing this issue for now.

**Comment by itZzenXX** [comment]
Re-opening this as I am having the same issues as before. Trying to build ungoogled chromium version 102 now but it results in the same esbuild error as before. 

build.log:
[build.log](http://ls.qorg11.net/files/ymSngWTi/build.txt)

**Comment by itZzenXX** [comment]
I got chromium vanilla version 104 built as it drops esbuild (or that issue is not longer prevalent). I will build ungoogled chromium once version 104 releases.

**Comment by frunzales** [comment]
Re-opening this, it fails with the same error as OP:

```
[1388/1400] touch obj/v8/third_party/inspector_protocol/crdtp.stamp
[1389/1400] x86_64-pc-linux-gnu-g++ -MMD -MF obj/v8/src/inspector/inspector/value-mirror.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_L
ARGEFILE64_SOURCE -DNO_UNWIND_TABLES -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DV8_INTL_SUPPORT -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_ATOMIC_OBJECT_FIELD_WRITES -DV8_ENABLE_LAZY_SOURCE_POSITIO
NS -DV8_SHARED_RO_HEAP -DV8_WIN64_UNWINDING_INFO -DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH -DV8_SHORT_BUILTIN_CALLS -DV8_EXTERNAL_CODE_SPACE -DV8_ENABLE_MAGLEV -DV8_ENABLE_WEBASSEMBLY -DV8_ALLOCATION_FOLDING -DV8_ALLOCATION_SITE_TRA
CKING -DV8_ADVANCED_BIGINT_ALGORITHMS -DV8_USE_ZLIB -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_ENABLE_SANDBOX -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DCPPGC_YOUNG_GENERATION -DCPPG
C_POINTER_COMPRESSION -DV8_TARGET_ARCH_X64 -DV8_HAVE_TARGET_OS -DV8_TARGET_OS_LINUX -I../.. -Igen -I../../v8/include -I../../v8 -Igen/v8 -Igen/v8/include -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -Wno-unused-local-typed
efs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-t
ables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wno-strict-overflow -Wno-return-type -Wno-int-in-bool-context
 -O3 -fdata-sections -ffunction-sections -Wno-narrowing -Wno-class-memaccess -std=gnu++17 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden  -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -march=alderlake -pipe -Wno-builtin-macro-redefined -
c ../../v8/src/inspector/value-mirror.cc -o obj/v8/src/inspector/inspector/value-mirror.o
[1390/1400] x86_64-pc-linux-gnu-g++ -MMD -MF obj/v8/src/inspector/inspector/v8-debugger-agent-impl.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_S
OURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DV8_INTL_SUPPORT -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_ATOMIC_OBJECT_FIELD_WRITES -DV8_ENABLE_LAZY_SOUR
CE_POSITIONS -DV8_SHARED_RO_HEAP -DV8_WIN64_UNWINDING_INFO -DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH -DV8_SHORT_BUILTIN_CALLS -DV8_EXTERNAL_CODE_SPACE -DV8_ENABLE_MAGLEV -DV8_ENABLE_WEBASSEMBLY -DV8_ALLOCATION_FOLDING -DV8_ALLOCATIO
N_SITE_TRACKING -DV8_ADVANCED_BIGINT_ALGORITHMS -DV8_USE_ZLIB -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_ENABLE_SANDBOX -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DCPPGC_YOUNG_GENERAT
ION -DCPPGC_POINTER_COMPRESSION -DV8_TARGET_ARCH_X64 -DV8_HAVE_TARGET_OS -DV8_TARGET_OS_LINUX -I../.. -Igen -I../../v8/include -I../../v8 -Igen/v8 -Igen/v8/include -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -Wno-unused-l
ocal-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fn
o-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wno-strict-overflow -Wno-return-type -Wno-int-in-bo
ol-context -O3 -fdata-sections -ffunction-sections -Wno-narrowing -Wno-class-memaccess -std=gnu++17 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden  -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -march=alderlake -pipe -Wno-builtin-macro-r
edefined -c ../../v8/src/inspector/v8-debugger-agent-impl.cc -o obj/v8/src/inspector/inspector/v8-debugger-agent-impl.o
[1391/1400] touch obj/v8/src/inspector/inspector.stamp
[1392/1400] touch obj/v8/v8_base_without_compiler.stamp
[1393/1400] touch obj/v8/torque_generated_initializers.stamp
[1394/1400] touch obj/v8/v8_compiler.stamp
[1395/1400] touch obj/v8/v8_turboshaft.stamp
[1396/1400] touch obj/v8/v8_compiler_for_mksnapshot.stamp
[1397/1400] x86_64-pc-linux-gnu-g++ -MMD -MF obj/v8/v8_initializers/code-stub-assembler.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LA
RGEFILE64_SOURCE -DNO_UNWIND_TABLES -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DV8_INTL_SUPPORT -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_ATOMIC_OBJECT_FIELD_WRITES -DV8_ENABLE_LAZY_SOURCE_POSITION
S -DV8_SHARED_RO_HEAP -DV8_WIN64_UNWINDING_INFO -DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH -DV8_SHORT_BUILTIN_CALLS -DV8_EXTERNAL_CODE_SPACE -DV8_ENABLE_MAGLEV -DV8_ENABLE_WEBASSEMBLY -DV8_ALLOCATION_FOLDING -DV8_ALLOCATION_SITE_TRAC
KING -DV8_ADVANCED_BIGINT_ALGORITHMS -DV8_USE_ZLIB -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_ENABLE_SANDBOX -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DCPPGC_YOUNG_GENERATION -DCPPG$
_POINTER_COMPRESSION -DV8_TARGET_ARCH_X64 -DV8_HAVE_TARGET_OS -DV8_TARGET_OS_LINUX -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DU_IMPORT=U_EXPORT -I../.. -Igen -I../../v8 -I../../v8/include -Igen/v8 -Igen/v8/include -Ig
en/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -Igen/shim_headers/zlib_shim -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-missing-field-initializers
-Wno-unused-parameter -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__=
 -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wno-strict-overflow -Wno-return-type -Wno-int-in-bool-context -O3 -fdata-sections -ffunction-sections -Wno-narrowing -Wno-class-memaccess -std=gnu++17 -fno-exceptions -fno-rtti -fvisibility
-inlines-hidden  -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -march=alderlake -pipe -Wno-builtin-macro-redefined -c ../../v8/src/codegen/code-stub-assembler.cc -o obj/v8/v8_initializers/code-stub-assembler.o
[1398/1400] touch obj/v8/v8_initializers.stamp
[1399/1400] touch obj/v8/v8_init.stamp
[1400/1400] python3.11 "../../build/toolchain/gcc_link_wrapper.py" --output="./mksnapshot" -- x86_64-pc-linux-gnu-g++ -pie -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -rdynamic -Wl,-z,defs -Wl,--as-needed -pie -Wl,--dis
able-new-dtags -Wl,-O2 -Wl,--gc-sections -Wl,--as-needed -o "./mksnapshot" -Wl,--start-group @"./mksnapshot.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -licui18n -licuuc -licudata -lz
ninja -v -j16 -l0 -C out/Release v8_context_snapshot_generator
ninja: Entering directory `out/Release'
ninja: error: '../../third_party/devtools-frontend/src/third_party/esbuild/esbuild', needed by 'gen/third_party/devtools-frontend/src/inspector_overlay/common.js', missing and no known rule to make it
 * ERROR: www-client/ungoogled-chromium-107.0.5304.87_p1::pf4public failed (compile phase):
 *   ninja -v -j16 -l0 -C out/Release v8_context_snapshot_generator failed
 *
 * Call stack:
 *     ebuild.sh, line  122:  Called src_compile
 *   environment, line 4595:  Called eninja '-C' 'out/Release' 'v8_context_snapshot_generator'
 *   environment, line 2484:  Called die
 * The specific snippet of code:
 *       "$@" || die "${nonfatal_args[@]}" "${*} failed"
 *
 * If you need support, post the output of `emerge --info '=www-client/ungoogled-chromium-107.0.5304.87_p1::pf4public'`,
 * the complete build log and the output of `emerge -pqv '=www-client/ungoogled-chromium-107.0.5304.87_p1::pf4public'`.
 *
 * MemTotal:       32584348 kB
 * SwapTotal:             0 kB
 *
 * The complete build log is located at '/var/tmp/portage/www-client/ungoogled-chromium-107.0.5304.87_p1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-client/ungoogled-chromium-107.0.5304.87_p1/temp/environment'.
 * Working directory: '/var/tmp/portage/www-client/ungoogled-chromium-107.0.5304.87_p1/work/chromium-107.0.5304.87'
 * S: '/var/tmp/portage/www-client/ungoogled-chromium-107.0.5304.87_p1/work/chromium-107.0.5304.87'

>>> Failed to emerge www-client/ungoogled-chromium-107.0.5304.87_p1, Log file:

>>>  '/var/tmp/portage/www-client/ungoogled-chromium-107.0.5304.87_p1/temp/build.log'
```
[build.log](https://github.com/PF4Public/gentoo-overlay/files/9915492/build.log)

**Comment by frunzales** [comment]
@PF4Public will give it a try and report back.

**Comment by frunzales** [comment]
same error with the clang flag enabled. the build fails at the same step:
```
[1400/1400] python3.11 "../../build/toolchain/gcc_link_wrapper.py" --output="./mksnapshot" -- x86_64-pc-linux-gnu-clang++ -pie -Wl,--build-id -fPIC -Wl,-z,noex
ecstack -Wl,-z,relro -Wl,-z,now -no-canonical-prefixes -rdynamic -Wl,-z,defs -Wl,--as-needed -pie -Wl,--disable-new-dtags -Wl,-O2 -Wl,--gc-sections -Wl,--as-ne
eded -o "./mksnapshot" -Wl,--start-group @"./mksnapshot.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -licui18n -licuuc -licudata -lz
ninja -v -j16 -l0 -C out/Release v8_context_snapshot_generator
ninja: Entering directory `out/Release'
ninja: error: '../../third_party/devtools-frontend/src/third_party/esbuild/esbuild', needed by 'gen/third_party/devtools-frontend/src/inspector_overlay/common.
js', missing and no known rule to make it
```

**Comment by PF4Public** [comment]
Please try patches from "KISS Community" as mentioned above in https://github.com/PF4Public/gentoo-overlay/issues/142#issuecomment-1088605666

**Comment by frunzales** [comment]
enabling the 'official' use flag fixes the issue on my side, compilation goes further.

**Comment by PF4Public** [comment]
Well, it is enabled by default :)

**Comment by PF4Public** [comment]
I suspect this could be fixed by `devtools_skip_typecheck=false`. I'll add it to ebuild soon.

**Comment by d-e-s-o** [comment]
> I suspect this could be fixed by `devtools_skip_typecheck=false`. I'll add it to ebuild soon.

FWIW, that configuration did solve this problem for me.
